- name: Get a token and run a flow
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - debug:
        msg: "Let's call the OO API"

    - name: Get OO CSRF Token for authentication
      uri:
        url: https://oo3.museumhof.net:8443/oo/rest/v2/executions
        user: oo
        password: oo
        method: GET
        force_basic_auth: true
        validate_certs: no
      register: results

    - debug:
        var: results.x_csrf_token

    - name: Run a flow
      uri:
        url: https://oo3.museumhof.net:8443/oo/rest/v2/executions
        user: oo
        password: oo
        method: POST
        use_proxy: false
        return_content: true
        force_basic_auth: true
        validate_certs: no
        headers:
          Content-Type: application/json
          X-CSRF-TOKEN-OO: "{{ results.x_csrf_token }}"
        status_code: 201
        body_format: json
        body:
          flowUuid: io.cloudslang.base.samples.utils.ping_target_host
          logLevel: STANDARD
          inputPromptUseBlank: false
          triggerType: MANUAL
          runName: Ansible Ping target host
      register: results

    - debug:
        var: results.content
